// Generated by gencpp from file beginner_tuto/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTO_MESSAGE_ADDTWOINTS_H
#define BEGINNER_TUTO_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <beginner_tuto/AddTwoIntsRequest.h>
#include <beginner_tuto/AddTwoIntsResponse.h>


namespace beginner_tuto
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace beginner_tuto


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tuto::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::beginner_tuto::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::beginner_tuto::AddTwoInts > {
  static const char* value()
  {
    return "beginner_tuto/AddTwoInts";
  }

  static const char* value(const ::beginner_tuto::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tuto::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::beginner_tuto::AddTwoInts > 
template<>
struct MD5Sum< ::beginner_tuto::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tuto::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tuto::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tuto::AddTwoIntsRequest> should match 
// service_traits::DataType< ::beginner_tuto::AddTwoInts > 
template<>
struct DataType< ::beginner_tuto::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tuto::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tuto::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tuto::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::beginner_tuto::AddTwoInts > 
template<>
struct MD5Sum< ::beginner_tuto::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tuto::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tuto::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tuto::AddTwoIntsResponse> should match 
// service_traits::DataType< ::beginner_tuto::AddTwoInts > 
template<>
struct DataType< ::beginner_tuto::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tuto::AddTwoInts >::value();
  }
  static const char* value(const ::beginner_tuto::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTO_MESSAGE_ADDTWOINTS_H
